[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "https://api.allorigins.win/get?url=:splat"
  status = 200
  force = true
  conditions = {Type = "request"}

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
