[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/api/news"
  to = "https://api.allorigins.win/get?url=https://lenta.ru/rss"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
